# Generated by Django 6.0.5 on 2026-09-03 09:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('issuers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('AADHAAR', 'Aadhaar Card'), ('MARKSHEET', 'Marksheet'), ('DEGREE', 'Degree Certificate'), ('CERTIFICATE', 'Other Certificate'), ('OTHER', 'Other')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('encrypted_file', models.FileField(upload_to='secure_docs/%Y/%m/')),
                ('original_filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('file_nonce', models.BinaryField()),
                ('data_key_nonce', models.BinaryField()),
                ('data_key_ciphertext', models.BinaryField()),
                ('file_sha256', models.CharField(db_index=True, max_length=64)),
                ('signature', models.BinaryField(blank=True, null=True)),
                ('status', models.CharField(choices=[('VERIFIED', 'Verified'), ('UNVERIFIED', 'Unverified')], default='UNVERIFIED', max_length=10)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('share_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('issuer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='issuers.issuer')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
