# Generated by Django 6.0.5 on 2026-09-03 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='share_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='share_max_views',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AddField(
            model_name='document',
            name='share_view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
