# Generated by Django 6.0.5 on 2026-09-03 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_share_expires_at_document_share_max_views_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='review_note',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('VERIFIED', 'Verified'), ('UNVERIFIED', 'Unverified'), ('PENDING', 'Pending Verification')], default='UNVERIFIED', max_length=10),
        ),
    ]
