# Generated by Django 6.0.5 on 2026-09-03 09:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Issuer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('issuer_type', models.CharField(choices=[('COLLEGE', 'College / University'), ('GOVERNMENT', 'Government (e.g. UIDAI-mock)'), ('OTHER', 'Other')], default='COLLEGE', max_length=20)),
                ('public_key_pem', models.TextField(editable=False)),
                ('private_key_nonce', models.BinaryField()),
                ('private_key_ciphertext', models.BinaryField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('staff', models.ManyToManyField(blank=True, limit_choices_to={'role': 'ISSUER'}, related_name='issuer_memberships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
