# Generated by Django 6.0.5 on 2026-09-03 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuer',
            name='issuer_type',
            field=models.CharField(choices=[('COLLEGE', 'College (identity / admission verification)'), ('UNIVERSITY', 'University (marksheets & degrees)'), ('GOVERNMENT', 'Government (e.g. UIDAI-mock)'), ('OTHER', 'Other')], default='COLLEGE', max_length=20),
        ),
    ]
